// Class catalog, part 1: Arcanist, Barbarian, Bard, Cleric, and Druid categories.
// Source: DCC RPG Core Rulebook (Royal Court Edition), printed pp. 142-150.
import type { CatalogClass } from "./raceclass";

export const CLASSES_1: CatalogClass[] = [
  {
    name: "Boring Ol' Arcanist",
    classTypes: ["Arcanist"],
    statBonuses: { int: 3, dex: 2 },
    skillGrants: [
      { name: "Arcane", ranks: 5, toRank20: true },
      { name: "Salvage", ranks: 3 },
      { name: "Crafting Skill of choice", ranks: 2 },
      { name: "Crafting Skill of choice", ranks: 1 },
    ],
    abilities: [
      "Tier 1 Arcanist crafting table",
      "One crafting Skill can be raised to Rank 20",
    ],
    drawbacks: [],
  },
  {
    name: "Alchemist",
    classTypes: ["Arcanist"],
    statBonuses: { con: 3, int: 3 },
    skillGrants: [
      { name: "Alchemy", ranks: 5, toRank20: true },
      { name: "Infusion", ranks: 3 },
    ],
    abilities: [
      "Immunity to Poison",
      "Tier 1 Alchemy crafting table",
      "End of each floor: +1 to Alchemy and Infusion Skill Advancement Checks",
    ],
    drawbacks: [],
  },
  {
    name: "Douchy Wizard School Wand-Maker",
    classTypes: ["Arcanist"],
    statBonuses: { int: 5, str: 1, dex: 1, cha: -2 },
    skillGrants: [
      { name: "Arcane", ranks: 5, toRank20: true, note: "Rank 20 line printed as 'Arcanist Skill'" },
      { name: "Lore", ranks: 2 },
      { name: "Negotiation", ranks: 2 },
      { name: "Salvage", ranks: 2 },
    ],
    abilities: [
      "Tier 1 crafting table of your choice",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Infernocrafter",
    classTypes: ["Arcanist"],
    statBonuses: { str: 3, con: 3, dex: 1 },
    skillGrants: [
      { name: "Arcane", ranks: 5, toRank20: true },
      { name: "Smithing", ranks: 3 },
    ],
    abilities: [
      "Resistance to Fire damage",
      "Tier 1 Arcanist crafting table",
      "Tier 1 Smithing crafting table",
    ],
    drawbacks: [],
  },
  {
    name: "Prison Tattoo Artist",
    classTypes: ["Arcanist"],
    statBonuses: { con: 3, dex: 3, int: 2 },
    skillGrants: [
      { name: "Tattoo Artistry", ranks: 5, toRank20: true },
      { name: "Calligraphy", ranks: 3 },
      { name: "Dagger", ranks: 2 },
    ],
    abilities: [
      "Tier 1 Tattoo chair (crafting table)",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Boring Ol' Barbarian",
    classTypes: ["Barbarian"],
    statBonuses: { str: 6, con: 5 },
    skillGrants: [
      { name: "Weapon Skill of choice", ranks: 3 },
      { name: "Endurance", ranks: 2 },
      { name: "Intimidate", ranks: 1 },
    ],
    abilities: [
      "Rage: melee attacks deal +1 damage per Health Bar slot you have lost",
      "+2 DR Buff",
    ],
    drawbacks: [],
  },
  {
    name: "Gladiator",
    classTypes: ["Barbarian", "Bard"],
    statBonuses: { str: 3, con: 3, cha: 3 },
    skillGrants: [
      { name: "Weapon Skill of choice", ranks: 2, toRank20: true, note: "one Weapon Skill can be raised to Rank 20" },
      { name: "Performance", ranks: 2 },
      { name: "Intimidation", ranks: 2 },
      { name: "Attack of Opportunity", ranks: 1 },
    ],
    abilities: [
      "Rage: melee attacks deal +1 damage per Health Bar slot you have lost",
      "+1 DR Buff",
      "1/combat after a kill: Unopposed Performance Check; Amazing Success or better grants +1 Popularity",
    ],
    drawbacks: [],
  },
  {
    name: "Harii",
    classTypes: ["Barbarian", "Rogue"],
    statBonuses: { str: 1, dex: 1, int: 1 },
    skillGrants: [
      { name: "Ambush", ranks: 4 },
      { name: "Stealth", ranks: 4 },
      { name: "Weapon Skill of choice", ranks: 2 },
    ],
    abilities: [
      "Rage: melee attacks deal +1 damage per Health Bar slot you have lost",
      "+1 DR Buff",
      "Can see in total darkness",
      "Access to the Desperado Club",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Feral Cat Berserker",
    classTypes: ["Barbarian"],
    statBonuses: { dex: 2, str: 2, cha: 2 },
    skillGrants: [
      { name: "Slice Attack", ranks: 3 },
      { name: "Unarmed Combat", ranks: 3 },
      { name: "Dodge", ranks: 2 },
      { name: "Ambush", ranks: 1 },
    ],
    abilities: [
      "Rage: melee attacks deal +1 damage per Health Bar slot you have lost",
      "+1 DR Buff",
      "Can see in total darkness",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Limited Class: cat-based Races only (Cat, Cat Girl, Tigran, etc.); Earth Class",
  },
  {
    name: "Shieldmaiden",
    classTypes: ["Barbarian", "Fighter"],
    statBonuses: { str: 3, dex: 3, cha: 3, int: -2 },
    skillGrants: [
      { name: "Shield Block", ranks: 5 },
      { name: "Weapon Skill of choice", ranks: 2, toRank20: true, note: "one Weapon Skill can be raised to Rank 20" },
    ],
    abilities: [
      "Rage: melee attacks deal +1 damage per Health Bar slot you have lost",
      "+1 DR Buff",
      "Add STR Mod a second time to melee attack damage against males",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Limited Class: female crawlers only; Earth Class",
  },
  {
    name: "Boring Ol' Bard",
    classTypes: ["Bard"],
    statBonuses: { cha: 3 },
    skillGrants: [
      { name: "Performance", ranks: 3 },
      { name: "Weapon Skill of choice", ranks: 1 },
      { name: "Spell of choice", ranks: 2, note: "spell" },
      { name: "Diplomacy", ranks: 2 },
      { name: "Good First Impression", ranks: 1 },
      { name: "Lore", ranks: 1 },
    ],
    abilities: [
      "Access to all membership-based clubs regardless of current memberships",
      "Membership in the Dungeon Book of the Floor Club (all Spells)",
      "Free room at all saferooms",
      "May gain access to a Patron",
    ],
    drawbacks: ["Pay +1 Mana to cast Spells that are not 'Favored: Bard'"],
  },
  {
    name: "Artist Alley Mogul",
    classTypes: ["Bard", "Merchant"],
    statBonuses: { dex: 5, cha: 5 },
    skillGrants: [
      { name: "Dodge", ranks: 2, toRank20: true },
      { name: "Negotiation", ranks: 2 },
      { name: "Pathfinder", ranks: 2 },
      { name: "Shield", ranks: 2, note: "spell" },
    ],
    abilities: [
      "25% discount at all stores; +15% to money earned from sales",
      "10% interest on all coins upon descent to the next floor",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Former Child Actor",
    classTypes: ["Bard"],
    statBonuses: { cha: 10 },
    skillGrants: [
      { name: "Character Actor", ranks: 3, note: "Rank increases only upon descent to the next floor" },
      { name: "Cockroach", ranks: 2 },
    ],
    abilities: [
      "+1 to Skill Advancement Checks for Charisma-based Skills",
      "Immunity to Poison and all diseases",
      "The Manager Benefit",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "'Cut!' achievement, 1+ trillion views, Popularity 3+; Earth Class",
  },
  {
    name: "NecroBard",
    classTypes: ["Bard", "Necromancer"],
    statBonuses: { int: 3, con: 3, cha: 3, str: -2 },
    skillGrants: [
      { name: "Performance", ranks: 4 },
      { name: "Turn Undead", ranks: 3, note: "spell" },
      { name: "Panty Dropper", ranks: 3, note: "spell" },
    ],
    abilities: [
      "Access to all membership-based clubs regardless of current memberships",
      "Free room at all saferooms",
      "Must choose an entertainment-based Skill (singing, kazoo, storytelling, etc.)",
    ],
    drawbacks: ["Pay +1 Mana to cast Spells that are not 'Favored: Bard' or that don't deal Necrotic damage"],
  },
  {
    name: "Poet Laureate",
    classTypes: ["Bard"],
    statBonuses: { int: 3, cha: 2 },
    skillGrants: [
      { name: "Performance (written word specialty)", ranks: 5, toRank20: true },
      { name: "Earworm", ranks: 2, note: "spell; as spoken word poetry" },
      { name: "Heal Others", ranks: 2, note: "spell" },
      { name: "Shield", ranks: 2, note: "spell" },
    ],
    abilities: [
      "Access to all membership-based clubs regardless of current memberships",
      "Must choose a Patron; GM offers at least two candidates at Class selection",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: ["Pay +1 Mana to cast Spells that are not 'Favored: Bard'"],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Professional Roadie",
    classTypes: ["Bard", "Rogue"],
    statBonuses: {},
    skillGrants: [
      { name: "Performance (guitar specialty)", ranks: 4 },
      { name: "Negotiation", ranks: 3 },
      { name: "Iron Stomach", ranks: 1 },
      { name: "Repair", ranks: 1 },
    ],
    abilities: [
      "+8 stat points split among STR, CON, and CHA (player's choice)",
      "Advantage on Checks against Poison or effects that inflict the Shit-Faced Debuff",
      "At combat start, may declare all damage you deal is Sonic",
      "Advantage on Repair Skill Checks",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: [],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Spellbinder",
    classTypes: ["Bard"],
    statBonuses: { cha: 2, int: 2 },
    skillGrants: [
      { name: "Good First Impression", ranks: 2 },
      { name: "Lore", ranks: 2 },
      { name: "Performance", ranks: 2 },
      { name: "Hot Stuff Aura", ranks: 2, note: "spell" },
      { name: "Panty Dropper", ranks: 2, note: "spell" },
    ],
    abilities: [
      "Add CHA Mod a second time on CHA Skill Checks in potentially hostile situations",
      "Access to the Spellbook of the Floor club ('Favored: Bard' Spells only)",
      "1/day: captivate everyone on the battlefield for a round, preventing attacks (party, Mobs, minions; not Bosses)",
    ],
    drawbacks: [],
  },
  {
    name: "Boring Ol' Cleric",
    classTypes: ["Cleric"],
    statBonuses: { cha: 4, int: 3 },
    skillGrants: [
      { name: "Weapon Skill of choice", ranks: 2 },
      { name: "Religion", ranks: 3 },
      { name: "Heal Others", ranks: 2, note: "spell" },
      { name: "Shield", ranks: 2, note: "spell" },
      { name: "Turn Undead", ranks: 2, note: "spell" },
    ],
    abilities: [
      "Access to the Spell Book of the Level club ('Favored: Cleric' Spells only)",
      "Access to Club Vanquisher",
    ],
    drawbacks: [
      "Must worship a deity",
      "Cannot choose a Cleric-type Class if you have access to the Desperado Club",
    ],
  },
  {
    name: "Black Inquisitor General",
    classTypes: ["Cleric", "Mage", "Paladin"],
    statBonuses: { str: 3, int: 3, cha: 1, con: -2 },
    skillGrants: [
      { name: "Find Trap", ranks: 3 },
      { name: "Weapon Skill of choice", ranks: 3 },
      { name: "Trap Engineer", ranks: 2 },
      { name: "Spell of choice", ranks: 2, note: "spell" },
      { name: "Religion", ranks: 1 },
    ],
    abilities: [
      "Can see in total darkness",
      "Access to all membership-based clubs regardless of current memberships",
    ],
    drawbacks: ["Must worship a deity"],
  },
  {
    name: "Santero",
    classTypes: ["Cleric"],
    statBonuses: { str: 3, cha: 3, con: 2, int: -2 },
    skillGrants: [
      { name: "Heal Others", ranks: 2, note: "spell" },
      { name: "Shield", ranks: 2, note: "spell" },
      { name: "Soul Collector", ranks: 2, note: "spell" },
      { name: "Weapon Skill of choice", ranks: 2 },
      { name: "Religion", ranks: 2 },
      { name: "Endurance", ranks: 1 },
    ],
    abilities: [
      "Access to the Dungeon Book of the Floor club ('Favored: Cleric' Spells only)",
      "Access to Club Vanquisher",
    ],
    drawbacks: [
      "Must worship a deity",
      "Cannot choose this Class if you have access to the Desperado Club",
    ],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Boring Ol' Druid",
    classTypes: ["Druid"],
    statBonuses: { int: 2, con: 2, dex: 2 },
    skillGrants: [
      { name: "Nature's Breath", ranks: 3, note: "spell" },
      { name: "Spell of choice", ranks: 3, note: "spell" },
      { name: "Spell of choice", ranks: 2, note: "spell" },
      { name: "Survival", ranks: 2 },
    ],
    abilities: [
      "Mana recovers at twice the normal rate in a natural environment",
      "Access to the Dungeon Book of the Floor club ('Favored: Druid' Spells only)",
    ],
    drawbacks: [],
  },
  {
    name: "Herbalist",
    classTypes: ["Arcanist", "Druid"],
    statBonuses: { con: 2, int: 2 },
    skillGrants: [
      { name: "Alchemy", ranks: 2 },
      { name: "Cooking", ranks: 2 },
      { name: "First Aid", ranks: 2 },
      { name: "Survival", ranks: 2 },
      { name: "Nature's Breath", ranks: 2, note: "spell" },
      { name: "Dirt Clod", ranks: 2, note: "spell" },
    ],
    abilities: ["Mana recovers at twice the normal rate in a natural environment"],
    drawbacks: [],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
  {
    name: "Lifebringer",
    classTypes: ["Druid"],
    statBonuses: { con: 2, int: 1 },
    skillGrants: [
      { name: "First Aid", ranks: 2 },
      { name: "Pathfinder", ranks: 2 },
      { name: "Regeneration", ranks: 2 },
      { name: "Survival", ranks: 2 },
      { name: "Nature's Breath", ranks: 2, note: "spell" },
    ],
    abilities: [
      "+1 Rank in all Spells with the Heal keyword",
      "1/day: grant Regeneration at your Skill Rank to all party members within 30 ft for 10 minutes",
    ],
    drawbacks: [],
  },
  {
    name: "Physicker",
    classTypes: ["Druid"],
    statBonuses: { con: 3, int: 3 },
    skillGrants: [
      { name: "Nature's Breath", ranks: 3, note: "spell" },
      { name: "Oakhide", ranks: 3, note: "spell" },
      { name: "Rootfoot", ranks: 2, note: "spell" },
      { name: "Solsplash", ranks: 2, note: "spell" },
    ],
    abilities: [
      "Double Mana regeneration when outdoors",
      "1/day: grant +1 DR to your party for 1 scene",
    ],
    drawbacks: [],
  },
  {
    name: "Shepherd",
    classTypes: ["Druid"],
    statBonuses: { int: 2, cha: 2, con: 2 },
    skillGrants: [
      { name: "Animal Handling", ranks: 3 },
      { name: "Pathfinder", ranks: 2 },
      { name: "Nature's Breath", ranks: 2, note: "spell" },
      { name: "Drain Life", ranks: 2, note: "spell" },
    ],
    abilities: [
      "Can see twice as far as most creatures",
      "Mana recovers at twice the normal rate in a natural environment",
      "Gain a friendly Pet",
      "Pets in your Herd gain +2 DR",
      "Silver Earth Box with guaranteed Earth Hobby Potion",
    ],
    drawbacks: ["May not use melee weapons other than Herding Weapons (p. 182)"],
    prerequisites: "Earth Class: requires an Earth-based Race",
  },
];
