// Race catalog extracted from DCC RPG Core Rulebook (Royal Court Edition), pp. 128-141.
// Source notes: rules/extraction/core_pages_124-131.md, core_pages_132-139.md, core_pages_140-147.md.
import type { CatalogRace } from "./raceclass";

export const RACES: CatalogRace[] = [
  {
    name: "Amazonian",
    kind: "earth",
    statBonuses: { str: 6, dex: 3 },
    skillGrants: [
      { name: "Bow", ranks: 2 },
      { name: "Endurance", ranks: 2 },
      { name: "Pugilism", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "+2 DR",
      "Each floor: 1 free Weapon Training Guild coupon",
    ],
    drawbacks: [],
    prerequisites: "At least one Strength- or Dexterity-based Skill at Rank 5+",
  },
  {
    name: "Arachnid",
    kind: "earth",
    statBonuses: { dex: 5 },
    skillGrants: [
      { name: "Web Spell", ranks: 3, note: "Costs half normal Mana to cast" },
      { name: "Climbing", ranks: 2 },
      { name: "Perception", ranks: 2 },
      { name: "Performance", ranks: 2, note: "Stringed instrument specialty" },
    ],
    abilities: [
      "Size Medium (4)",
      "Innate Climb Move equal to normal Move, no Checks unless under duress",
    ],
    drawbacks: [],
  },
  {
    name: "Cat",
    kind: "earth",
    statBonuses: { dex: 4, con: 2, cha: 1, str: -3 },
    skillGrants: [
      { name: "Cat-like Reflexes", ranks: 3 },
      { name: "Slice Attack", ranks: 2 },
    ],
    abilities: [
      "Size Small (2); Animal",
      "See in total darkness",
      "Advantage on Cat-like Reflexes Checks",
      "Nine Lives: half damage from first 9 attacks each day",
    ],
    drawbacks: ["Double damage from Dogs and Beasts"],
    prerequisites: "Must already be a Cat",
  },
  {
    name: "Cat Girl/Cat Boy",
    kind: "earth",
    statBonuses: { dex: 3, cha: 3, con: -2 },
    skillGrants: [
      { name: "Cat-like Reflexes", ranks: 2 },
      { name: "Good First Impression", ranks: 2 },
      { name: "Light on your Feet", ranks: 2 },
      { name: "Slice Attack", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "Slice Attacks may use CHA Mod for damage instead of STR",
      "Toxoplasma G.: 1/day allies get Rank 5 Catcher (+5 DR Upgrade) for 1 round to protect you; users gain 1 AI Favor",
    ],
    drawbacks: [
      "Disadvantage on CHA-based Skill Checks with felines other than Cat Girls/Boys",
    ],
  },
  {
    name: "Changbi Demon",
    kind: "earth",
    statBonuses: { dex: 5, str: 3, con: 3, cha: -2 },
    skillGrants: [
      { name: "Ambush", ranks: 3 },
      { name: "Creepy Chains (Club)", ranks: 3 },
    ],
    abilities: [
      "Size Medium (4)",
      "Any chain usable as weapon (Club Skill, 10ft range); lengthen/shorten any chain 50% 1/scene",
      "Foes touching you with bare skin take 1d4+F Acid",
      "No need to breathe",
    ],
    drawbacks: ["Vulnerable to Holy damage", "Cannot worship a deity"],
  },
  {
    name: "Changeling",
    kind: "earth",
    statBonuses: { cha: 3, int: 2 },
    skillGrants: [
      { name: "Ambush", ranks: 2 },
      { name: "Deception", ranks: 2 },
      { name: "Escape Artist", ranks: 1 },
    ],
    abilities: [
      "Size Large (5)",
      "Advantage on Deception Checks when no talking needed",
      "Shapeshift: touch a Race to add it to library; Action + Unopposed Deception Check to assume it, gaining its bonuses except Stats and Skills",
      "Shifted form conveyed to Dungeon systems (HUDs, mini-maps)",
      "Free access to orgs/producers relevant to impersonated individual",
    ],
    drawbacks: ["Cannot touch mimic-type creatures"],
  },
  {
    name: "Crocodilian",
    kind: "earth",
    statBonuses: { str: 4, con: 3 },
    skillGrants: [
      { name: "Pugilism", ranks: 2 },
      { name: "Powerful Strike", ranks: 2 },
    ],
    abilities: [
      "Size Large (5)",
      "+3 DR Buff",
      "Advantage on Intimidate Checks when physically menacing in person",
      "+1 Buff to all Skill Checks for 1 hour after a full meal",
    ],
    drawbacks: [
      "Disadvantage on all CHA-based Checks while Fatigued",
    ],
  },
  {
    name: "Doppelgänger",
    kind: "earth",
    statBonuses: { con: 4, str: 3 },
    skillGrants: [
      { name: "Deception", ranks: 1 },
      { name: "Endurance", ranks: 1 },
    ],
    abilities: [
      "Size unchanged; changes when shifting",
      "+2 DR",
      "Max lift weight may use CON instead of STR",
      "Advantage on Escape Artist Checks, usable while Held or watched",
      "1/scene Action: incorporate held weapon into mass for +CON Mod damage; item cannot be disarmed",
      "Shape-Change (Action): any shape of comparable mass, items incorporated proportionally; costs 1 Health Bar slot; specific person/object requires Unopposed Deception Check",
    ],
    drawbacks: ["Cannot change mass, including worn/carried equipment"],
  },
  {
    name: "Dwarf, Classic",
    kind: "earth",
    statBonuses: { con: 4, int: 2, cha: -2 },
    skillGrants: [
      { name: "Crafting Skill (choice)", ranks: 3, note: "Two different crafting Skills of your choice" },
      { name: "Endurance", ranks: 2 },
      { name: "All crafting Skills", ranks: 0, toRank20: true },
    ],
    abilities: ["Size Medium (4)", "See in total darkness"],
    drawbacks: [
      "Disadvantage on all CHA-based Checks with elves or fairies",
    ],
  },
  {
    name: "Dwarf, Fathom",
    kind: "earth",
    statBonuses: { con: 3, str: 2 },
    skillGrants: [
      { name: "Engineering", ranks: 3 },
      { name: "Dumpster Diving", ranks: 2 },
      { name: "Salvage", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "Advantage on d20 Checks involving earth, rocks, and dirt",
      "Head lizard emits 15ft Cone of light; easily replaced if lost",
    ],
    drawbacks: [],
  },
  {
    name: "Elf, High",
    kind: "earth",
    statBonuses: { int: 4, dex: 4, cha: 4 },
    skillGrants: [
      { name: "Intimidation", ranks: 2, note: "May use CHA Mod" },
      { name: "Lore", ranks: 1 },
      { name: "Charisma-based Skill (choice)", ranks: 0, toRank20: true, note: "Two different CHA-based Skills" },
    ],
    abilities: [
      "Size Medium (4)",
      "Mana recovery x2 in natural environments",
      "+1d4 to Evade Checks",
    ],
    drawbacks: [
      "Disadvantage on all CHA-based Checks with Dwarves, Rat-Kin, or anyone smelly/dirty",
    ],
  },
  {
    name: "Elf, City",
    kind: "earth",
    statBonuses: {},
    skillGrants: [
      { name: "Good First Impression", ranks: 3 },
      { name: "Negotiation", ranks: 2 },
      { name: "Streetwise", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "+6 split as desired among INT, DEX, and CHA",
      "1/floor during a Long Rest: reassign the split points among INT, DEX, CHA",
      "First CHA Check on first entry to a settlement with Advantage; Amazing Success or better yields a permanent contact",
    ],
    drawbacks: [],
    note: "Book text says reassign \"the +4 spent\" but the bonus is +6; transcribed as printed, possible errata.",
  },
  {
    name: "Elf, Night",
    kind: "earth",
    statBonuses: { int: 3, dex: 3 },
    skillGrants: [
      { name: "Acute Ears", ranks: 3 },
      { name: "Hide in Shadows", ranks: 3, toRank20: true },
      { name: "Crafting Skill (choice)", ranks: 0, toRank20: true },
    ],
    abilities: [
      "Size Medium (4)",
      "See in total darkness",
      "Advantage on Hide in Shadows at night",
      "1/day: a living thing's shadow uses Taunt at Rank = Floor Number (no Stat Mod) to pull attacks away from you",
    ],
    drawbacks: [],
  },
  {
    name: "Frost Maiden",
    kind: "earth",
    statBonuses: { cha: 2, int: 2, dex: 2 },
    skillGrants: [{ name: "Persuasion", ranks: 2 }],
    abilities: [
      "Size Petite (3)",
      "Melee attacks deal +1d4 Ice",
      "Advantage on INT and CON Stat Checks",
      "Game Guide becomes your Manager",
      "Flight up to 1 minute per scene",
    ],
    drawbacks: [],
  },
  {
    name: "Human",
    kind: "earth",
    statBonuses: { str: 2, int: 2, con: 2, dex: 2, cha: 2 },
    skillGrants: [],
    abilities: [
      "Size typically Medium (4)",
      "End of each floor: 1 Skill Advancement Check with Advantage if that Skill is Rank 9 or less",
      "+1 AI Favor per level-up",
      "When damaged, may spend 1 AI Favor for DR equal to CON (repeatable per Favor)",
      "1/day: untrained non-Passive Utility Skill Check as if Rank 2",
      "1/floor Action: remove any single Debuff, including Injuries",
    ],
    drawbacks: [],
  },
  {
    name: "Igneous",
    kind: "earth",
    statBonuses: { con: 6, str: 4, int: -2, cha: -2 },
    skillGrants: [{ name: "Endurance", ranks: 1 }],
    abilities: [
      "Size Large (5)",
      "+3 DR Buff",
      "1/day: double Move for 20 seconds",
      "Action: CON Check; on Success deal 1d8+F Fire in 5ft Burst",
      "No Survival Checks in harsh heat; breathe underwater",
      "Immune to Fire damage",
      "Can burrow",
    ],
    drawbacks: [
      "Vulnerable to Ice damage",
      "Lose 1 Health Bar slot per Inventory access (Hotlist excluded)",
      "Disadvantage on Checks to conceal presence or nature (e.g. Stealth)",
    ],
  },
  {
    name: "Lajabless",
    kind: "earth",
    statBonuses: {},
    skillGrants: [
      { name: "Spell (choice)", ranks: 2, note: "Two Spells of your choice" },
      { name: "Weapon Skill (choice)", ranks: 3 },
    ],
    abilities: [
      "Size Medium (4)",
      "+5 INT during day, +5 STR during night",
      "Advantage on Ambush and Intimidation Skill use",
      "Day: STR halved, Spells cost half Mana; Night: STR doubled, Spells cost double Mana",
    ],
    drawbacks: [],
  },
  {
    name: "Obsidian Butterfly",
    kind: "earth",
    statBonuses: { dex: 3, int: 2, con: -4 },
    skillGrants: [
      { name: "Intimidate", ranks: 2 },
      { name: "Slice Attack", ranks: 2 },
      { name: "Spell (choice)", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "Four 15ft translucent wings can deliver touch/melee-range Spells",
      "May use CHA Mod instead of CON Mod for Health Bar",
      "+1d4 to Evade Checks",
      "On entering Sixth Floor choose: Stronger Wings (flight 2 min/scene, +20ft Move flying) or Ferocious Visage (Advantage on fear/respect Skills)",
    ],
    drawbacks: [],
    prerequisites: "Rank 5+ with any Edged Weapon",
  },
  {
    name: "Primal",
    kind: "earth",
    statBonuses: { str: -1, int: -1, con: -1, dex: -1, cha: -1 },
    skillGrants: [{ name: "All Skills", ranks: 0, toRank20: true }],
    abilities: [
      "Size unchanged",
      "Apply current Race's racial benefits; Race is listed as Primal",
    ],
    drawbacks: [],
  },
  {
    name: "Rat Hooligan",
    kind: "earth",
    statBonuses: { dex: 2, con: 1 },
    skillGrants: [
      { name: "Escape Plan", ranks: 2 },
      { name: "Stealth", ranks: 2 },
      { name: "Bite", ranks: 1 },
      { name: "Survival", ranks: 1 },
    ],
    abilities: [
      "Size Petite (3)",
      "Advantage on Checks to resist hunger and thirst",
      "Converse with house rats for minimal information in buildings",
      "Bite damage may use DEX Mod instead of STR",
    ],
    drawbacks: [],
  },
  {
    name: "Sasquatch",
    kind: "earth",
    statBonuses: { str: 6, con: 6, dex: 2, int: -3, cha: -1 },
    skillGrants: [
      { name: "Foot Soldier", ranks: 3 },
      { name: "Smush", ranks: 3, toRank20: true },
    ],
    abilities: ["Size Large (5)"],
    drawbacks: [],
    prerequisites: "Smush Skill Rank 5+",
  },
  {
    name: "Tetrakai",
    kind: "earth",
    statBonuses: { dex: 6, cha: -2 },
    skillGrants: [
      { name: "Pugilism", ranks: 2 },
      { name: "Wrasslin'", ranks: 2 },
      { name: "All Edged Weapon Skills", ranks: 1 },
    ],
    abilities: [
      "Size Medium (4)",
      "Four Arms: Hands/Holding Gear slot fits four items (or two two-handed weapons)",
    ],
    drawbacks: [],
  },
  {
    name: "Tigran",
    kind: "earth",
    statBonuses: { dex: 3, str: 2, cha: -4 },
    skillGrants: [
      { name: "Ambush", ranks: 2 },
      { name: "Cat-like Reflexes", ranks: 2 },
      { name: "Slice Attack", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "See in total darkness",
      "+1 DR Buff",
      "+10ft Move",
      "Melee attacks deal x2 total damage during a Surprise Action",
    ],
    drawbacks: [
      "Disadvantage on DEX-based Skills requiring fine manipulation or motor coordination",
    ],
  },
  {
    name: "Bune",
    kind: "alien",
    statBonuses: { int: 3, dex: 2, con: -2 },
    skillGrants: [
      { name: "Determine Value", ranks: 3 },
      { name: "Fabricate", ranks: 3 },
      { name: "Negotiation", ranks: 3 },
    ],
    abilities: [
      "Size Medium (4)",
      "At Level 50: +2 DEX and wings (fly up to 500ft per scene)",
      "+1 Popularity per Critical Hit in combat",
    ],
    drawbacks: ["No access to Earth Classes"],
    prerequisites: "Popularity 3+",
  },
  {
    name: "Caprid",
    kind: "alien",
    statBonuses: { int: 3, cha: 3, str: -2 },
    skillGrants: [
      { name: "Find Crawler", ranks: 3, toRank20: true },
      { name: "Investigation", ranks: 3 },
      { name: "Leadership", ranks: 3 },
      { name: "Persuasion", ranks: 0, toRank20: true },
    ],
    abilities: [
      "Size Large (5)",
      "+1 Popularity per Critical Hit on a CHA Skill Check or non-combat Spell Skill Check",
    ],
    drawbacks: ["No access to Earth Classes"],
  },
  {
    name: "Grulke",
    kind: "alien",
    statBonuses: { dex: 3, str: 2, cha: -2 },
    skillGrants: [
      { name: "Jumping or Light on Your Feet (choice)", ranks: 3 },
      { name: "Zone of Control", ranks: 2 },
      { name: "Reach Weapon Skill (choice)", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "Tongue Lashing: ranged attack, [Rank = Floor Number] + DEX to hit, 1d8+STR Bludgeoning, 30ft; +1d8 at Rank 5/10/15; Rank fixed to Floor Number",
      "+2 DR breastplate (Torso)",
      "+1 Popularity when a troll-type enemy licks you or on Amazing Success+ Attack vs a troll-type enemy",
      "+1 Popularity per Critical Hit on a larger foe in combat",
    ],
    drawbacks: [
      "Troll-type enemies have Advantage on Wrasslin' Checks vs you and lick you on success",
      "No access to Earth Classes",
    ],
    prerequisites: "Rank 5+ in Jumping or Light on Your Feet",
  },
  {
    name: "Hobgoblin",
    kind: "alien",
    statBonuses: { dex: 1, cha: -5 },
    skillGrants: [
      { name: "All Trap-based Skills", ranks: 3, toRank20: true },
      { name: "All Explosive-based Skills", ranks: 3, toRank20: true },
      { name: "Regeneration", ranks: 1 },
    ],
    abilities: [
      "Size Medium (4)",
      "Free access to all Hobgoblin Sapper Workshops",
      "End of each floor: 1 Explosive or Trap-based Skill Advancement Check with Advantage",
      "+1 Popularity per kill with a trap or explosive, 1/scene",
    ],
    drawbacks: ["Charisma capped at 10", "No access to Earth Classes"],
    prerequisites: "Rank 5+ in Explosives Handling and any Trap-based Skill",
  },
  {
    name: "Pocket Kuma",
    kind: "alien",
    statBonuses: { dex: 5, cha: 5, str: -4, con: -4 },
    skillGrants: [
      { name: "Bite", ranks: 2 },
      { name: "Dodge", ranks: 2 },
      { name: "Slice Attack", ranks: 2 },
      { name: "Ambush", ranks: 1 },
      { name: "Light on Your Feet", ranks: 0, toRank20: true },
    ],
    abilities: [
      "Size Small (2); Animal",
      "Advantage on all CHA-based Checks",
      "See in total darkness",
      "No falling damage",
      "+1 Popularity when acting in a Surprise Round or on a Critical Fail on an Evade Check",
    ],
    drawbacks: [
      "Strength capped at 10",
      "Half damage with STR-based melee weapons",
      "Vulnerable to Bludgeoning damage",
      "No access to Earth Classes",
    ],
  },
  {
    name: "Pterolykos",
    kind: "alien",
    statBonuses: { cha: 4, dex: 2 },
    skillGrants: [
      { name: "Bite", ranks: 3 },
      { name: "Performance", ranks: 3 },
      { name: "Tracking", ranks: 3 },
      { name: "Diplomacy", ranks: 1 },
    ],
    abilities: [
      "Size Medium (4)",
      "Wings: flight up to 50 seconds per scene",
      "+1 Popularity per Critical Hit on a CHA Skill Check",
    ],
    drawbacks: [
      "Disadvantage on all Checks to conceal emotion or presence (e.g. Deception, Stealth)",
      "No access to Earth Classes",
    ],
  },
  {
    name: "Skyfowl",
    kind: "alien",
    statBonuses: { dex: 3, cha: 3, str: -1, con: -1 },
    skillGrants: [
      { name: "Slice Attack", ranks: 2 },
      { name: "All Charisma-based Skills", ranks: 2 },
    ],
    abilities: [
      "Size Medium (4)",
      "Advantage on Perception for observing things 10+ feet away",
      "Flight up to 3 minutes per scene",
      "+1 Popularity per Critical Hit on Leadership, Perception, Persuasion, or Taunt Checks",
    ],
    drawbacks: [
      "Cleric-based Class clips wings: flight limited to 10-second hops per scene",
      "No access to Earth Classes",
    ],
  },
];
